### PR TITLE
Allow keying through history

### PR DESCRIPTION
**Pull request by gshenar**
Your extension is great! Thought it could use some command-line style ability to key up and down through your history so if you are testing you don't have to always use your mouse. This is something I found myself wanting so I just decided to add it. Feel free to merge if you like.

### CODE REVIEW

**Comment by gshenar** [comment]
@jankoenig thoughts?

**Comment by jankoenig** [comment]
Nice! Thanks a lot, we will take a look today

**Comment by gshenar** [comment]
Awesome, no rush, just wasn't sure if you guys had seen it

**Comment by aswetlow** [comment]
Sorry it took so long. Your PR is awesome. Thank you!

**Pull request merged**
